### PR TITLE
Fix various bugs, get code working, add logic network support

### PR DESCRIPTION
**Pull request by rj45**
So, I sat down with your mod and I fixed a bunch of bugs and got it working I think the way you had intended.

Please feel free to cherry pick fixes or write them yourself and just reference my PR. I very much don't want to ruin your fun, do as you please. I just thought since I got the mod fully working that I would share that with you just in case you would like it. I am totally okay with you just closing this PR and not looking at it.

That said, I fixed:
- issue preventing the outpost world from loading because of a syntax issue in the infinity express patch
- there was a few issues with the lua syntax in the main script
- the on hover overlay was way off in the .object file when placing -- I tweaked the numbers to be better but it's still off by a few pixels, might need a few more tweaks (this is the imagePosition for ION2_PharituIONDevice_radius.png)
- the indicator on/off code would always run, making the device always say something. I added a boolean flag to remember the state so it's not so chatty (not tested fully yet)
- I fixed the TransferPendingItemTo function so that it does what you intended. The `matches` method didn't exist, but you can compare the names of the items and that works
- Fixed a bunch of formatting and whitespace things -- sorry, my editor does this automatically. If you're reviewing the PR there's a way to ignore whitespace changes in the diff in the settings in the header of the files page

New Features:
- I added the ability to trigger the device with a logic network. If it's not connected to a logic network it won't self-trigger, you need to interact with it. But if it is connected to one, if it gets a true signal it will sort the contents of its container every 2.5 seconds or so
  - Note: it will not 'wake' containers like FU's item network devices will so it will not work properly if the player is out of the area. I haven't tested this extensively. But the advantage of not waking containers is less lag, so not sure if this should be fixed.

I think there's still a few bugs left, I haven't tested everything thoroughly. If you'd like some help fixing any remaining issues you can tag me in an issue and I might have time to take a look, I can't promise anything though.

### CODE REVIEW

**Comment by Exaelitus** [comment]
Hi Ryan!

First, thank you very much for taking the time to look at my mod ( It's basically my first! ).  That being said, I did not personally experience any of the bugs you mention.  The outpost loaded fine, and I tested the sorting with a couple blocks, food, and saplings ( etc ) and they seemed to work fine.  Also, I didn't notice the indicator "always running" at all.  There is a counter precisely for this reason.  I'm worried I might have uploaded the wrong iteration of my code...  I still very much appreciate your efforts, and expect that I surely just missed some things.

Second, -- "Fixed a bunch of formatting and whitespace things"  -- I'm afraid that I'm one of those religious zealots over formatting.  I greatly dislike the "scholastic indoctrination syntax" ( as I call it ) that is prevalent, even to the extent of being embedded in tools.  The days of compacting code to save hard-drive space are long gone, "LET THE CODE BREATHE!"  ;P     So, I won't be merging in your PR directly, but otherwise I would have.

I will integrate your changes as best I can, and give you credit in the update notes.  If there are any issues, I won't hold you accountable!  Feel free to contribute (or don't) at your leisure!

**Comment by Exaelitus** [comment]
( And yep!  Confirmed I stupidly didn't sync this repo with my ION2 workshop working directory, sorry about that.  The bugs you saw were already fixed in the mod on Steam.  *facepalm*  but I did integrate some of your changes, esp the new feature - which turns out was on my todo-list!  8)  )

**Comment by rj45** [comment]
Awesome yeah, I kind of thought it was an older version. I basically wanted to build almost exactly the same mod, so I pulled down your github repo, found it didn't work, fixed all the bugs, and then decided I wanted to integrate with the Frackin Universe item network instead of using radius so I started a fresh mod that wasn't based on yours. But since I fixed everything I thought I would upload it just in case you wanted to use any parts of it.

As for whitespace, I really should have turned the tool off before pushing and reverted all the changes it made. That's my bad. The point of formatting tools is to remove code format as a topic in code reviews. The style is nobody's favourite, but getting code reviews pointing out whitespace inconsistencies is a waste of time as well, so that's why I use a formatting tool. But it's your mod, you can format it how you wish and I respect that.

I don't need credit, but I am glad to be helpful.

**Comment by Exaelitus** [comment]
Again, THANK YOU for looking at my mod and fixing stuff!  Good luck with your mod and hope you have fun with it.  I happen to use FU myself, but I didn't want my mod to have a dependency on it since I know some people don't use it.

**Pull request closed without merging**
